### PR TITLE
Add steadforce branding

### PR DESCRIPTION
**Pull request by peters-david**
This pull requests adds Steadforce branding to the k8s escape room. A logo / banner has been added to the upper right.
The styling of the title has also been upated, according to the design by the marketing team.

Also, there was an issue with displaying the background image. A part of the top and bottom of the image were cut off.
The aspect ratio is corrected in this pull request and the visual elements of orb, tomb, cat and magic frame are repositioned to be in the same spot as before the adjustment of the backgrounds aspect ratio.

### CODE REVIEW

**Comment by steadyk** [comment]
@peters-david Thanks for the effort! Works fine locally!

There are two optional points which I would like to point out:

**1. Title and logo alignment**
Currently the title and logo are not in line with each other, which looks a bit odd to me. Could we maybe place the title at the same height as the logo? Maybe also as one line? But this might be a matter of taste and totally optional.

**2. Background image visability**
The areas were probably just cropped to cover the whole monitor space. But this might be also dependent of the monitor aspect ratio and resolution. It feels valid to me to have the whole picture visible. At least on my side I now have white spaces around the picture or a cropped picture if I zoom in. Would it be possible to maybe zoom out a bit, so that the whole picture will always be visible at a whole on most of the common monitors? And change the background from white to something in the same area as the background? This allows someone, who opens this site, to see in most of the cases the whole picture and can zoom in if needed.
But this might be an own issue not directly related to the branding.

Does this make sense? What do you and the others think?

In the end the points are just optional feelings from my side.

**Review by steadyk — CHANGES_REQUESTED** [review]
Looks really nice! Thanks!

The only tiny point might be that the red circles around the riddles are not always centric on zooming. But that's not a problem at all for me!

Thanks a lot for the effort! :-)

Maybe you could update the `k8s-escape-room-web-unsolved.png` image to the current version?

**Comment by peters-david** [comment]
We agreed to not improve on the circles not zooming centric and the circles not being perfectly centered over the items.
We may want to change this in the future.
The `k8s-escape-room-web-unsolved.png` was updated @steadyk .

**Review by steadyk — APPROVED** [review]
Thanks! Looks good to me! :-)

**Pull request merged**
