### PR TITLE
Install add ons

### PR DESCRIPTION
**Pull request by MarDipp**
See here for a first add-on: [https://github.com/steadforce/k8s-escape-room-basement](https://github.com/steadforce/k8s-escape-room-basement)

### CODE REVIEW

**Comment by steadyk** [comment]
Works fine for me with test folders containing test `install.sh` scripts. Thanks!

Do we also want to update the "k8s-escape-room-terminal.png"? There we should avoid any personal information on the image.
But we could also keep it as it is for now since the changes are only minor, we my adapt them in the future and it's probably not important.

One additional optional point:
The add-op folder paths are currently relative to the k9s-escape-room folder. E.g.: `. init.sh ../k8s-escape-room-basement/`. Is this fine for us or should we use absolute paths for the add-ons?

**Comment by MarDipp** [comment]
I would leave the picture "k8s-escape-room-terminal.png" as it is. I think it would just be a bit confusing to describe the installation of add ons without there being any add ons

It is sufficient to describe the modified init command in the readme of the add-on.

**Comment by MarDipp** [comment]
Only the folder in which the escape room is located is mounted in the workbench. If the add-on is not located next to the escape room, it is not so easy to access it from the workbench.

**Comment by steadyk** [comment]
> Only the folder in which the escape room is located is mounted in the workbench. If the add-on is not located next to the escape room, it is not so easy to access it from the workbench.

I guess the workbench mounts are different depending on the workbench (Linux, Windows, Codespaces).
For me it worked on the Linux workbench, since the whole `$HOME` is mounted there.

But yes, relative paths might be less error prone then absolutes. Fine for me!

Maybe we need to provide an additional mount option on the workbenches to make sure that the add-on folder(s) are mounted properly?

We might also need to find a way to using the add-ons on the Github codespaces, but this could be also something which we want to discuss in an own issue.

What do you think?

**Comment by MarDipp** [comment]
I see no benefit in developing the add-ons somewhere else. For me, the folder next to the escape room is just right. Additional mount points just make the workbench more complicated.

I think the missing tests and the support of codespaces can be handled via issues. Then we can work on the riddles and the infrastructure in parallel.

**Review by steadyk — APPROVED** [review]
Looks good to me! Thanks! :-)

**Pull request merged**
