### PR TITLE
Serve frontend directly at http://localhost/

### PR DESCRIPTION
**Pull request by MarDipp**

### CODE REVIEW

**Comment by steadyk** [comment]
We may also need to update:
* the welcomemessage
* the pictures which show the welcomemessage (but this might be not important)
* our documentation in Confluence

**Comment by steadyk** [comment]
Works fine for me on local setup as well as on Github codespaces! :-)

**Review by peters-david — CHANGES_REQUESTED** [review]
It works fine at localhost! The things mentioned by @steadyk should be changed imho (https://github.com/steadforce/k8s-escape-room/pull/57#issuecomment-2360117501).

**Comment by MarDipp** [comment]
> We may also need to update:
> 
>     * the welcomemessage
> 
>     * the pictures which show the welcomemessage (but this might be not important)
> 
>     * our documentation in Confluence

The welcome message, the screenshot of the terminal and the documentation in confluence now use the short url

**Review by peters-david — APPROVED** [review]
Looking good 👍🏼

**Pull request merged**
